language: python
sudo: required
python:
 - "3.5"
 - "3.6"
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
 - pip3 install -r requirements.txt
script:
 - sudo python3 setup.py install
 - python3 test/test.py
