language: python
python:
 - "3.5"
 - "3.6"
virtualenv:
  system_site_packages: true
install:
  - pip install .
  - pip install -r requirements.txt
script:
 - sudo python3 setup.py install
 - persepolis --version
