language: python
sudo: required
python:
 - "3.5"
 - "3.6"
before_install:
 - "pip install -U pip"
install:
 - pip install -r requirements.txt
script:
 - sudo python setup.py install
 - python test/test.py
