language: python
sudo: required
python:
 - "3.5"
 - "3.6"
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y python3
 - sudo apt-get install -y python3-setuptools
install:
 - pip3 install -r requirements.txt
script:
 - sudo python3 setup.py install
 - python3 test/test.py
